# Generated by Django 4.2.16 on 2026-06-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.staffmember')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
